# Site
name: "Petty Chen"
title: "Petty Chen"
description: "Doctor ğŸ‘©ğŸ»â€âš•ï¸, Director of Healthcare Products ğŸ‘©ğŸ»â€ğŸ’», & Mother of 1 ğŸ¼ğŸ‘¶ğŸ»"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://mailchimp.us1.list-manage.com/subscribe/post?u=9f054fd8365ff0e92bc6b6513&amp;id=2628970430'
include: ["_pages"]
permalink: /:title/
email: petty.chen@alumni.harvard.edu

# Authors
authors:
  petty:
    name: Petty
    display_name: Petty
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: petty.chen@alumni.harvard.edu
    twitter: https://twitter.com/pettypychen
    description: "MD, MPH, and FRSPH"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
